AllCops:
  TargetRubyVersion: 3.1.2
  EnabledByDefault: true
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'

require:
  - rubocop-rails

inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml

Style:
  Enabled: false

Metrics:
  Enabled: false

Lint:
  Enabled: true

Lint/ConstantResolution:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/NumberConversion:
  Enabled: false

Rails:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: false

Rails/DefaultScope:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/Date:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/RequestReferer:
  Enabled: false
