test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 15432
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: activerecord_multirange_test
